#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
# ------------------------------------------------------------------------------

cleanCase0





# # Source tutorial clean functions
# . $WM_PROJECT_DIR/bin/tools/CleanFunctions

# cleanCase

# foamCleanPolyMesh -region air
# foamCleanPolyMesh -region buildings

# rm -f constant/air/F*
# rm -f constant/air/constructMap*
# rm -f constant/air/finalAgglom*
# rm -f constant/air/globalFaceFaces*
# rm -f constant/air/subMap*
# rm -f constant/air/skyViewCoeff*
# rm -f constant/air/sunViewCoeff*
# rm -f constant/air/sunskyMap*
# rm -f constant/air/solarLoadFineFaces*

# rm -f 0/air/viewFactorField*

# rm -f 0/*.gz

# rm -rf ./constant/extendedFeatureEdgeMesh
# rm -f ./constant/triSurface/buildings_refined.eMesh*

# ----------------------------------------------------------------- end-of-file
