#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
# ------------------------------------------------------------------------------


# ./Allprepare

# Sim --------------------
rm -rf proc*
rm log.de*
rm log.re*
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructParMesh -constant
runApplication reconstructPar
rm -rf proc*

# Post -------------------
touch foam.foam



# ----------------------------------------------------------------- end-of-file
