#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication setFields

touch bubble_ADM.foam

# runApplication $(getApplication)

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar

# runParallel -s "reconstruct" redistributePar -reconstruct -latestTime

rm -r proc*


#------------------------------------------------------------------------------
