#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

(cd ADM && ./Allclean)

(cd icoReactingMultiphaseInterFoam && ./Allclean)

#------------------------------------------------------------------------------
