#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

# Run the ADM case
(cd ADMultiFoam && ./Allrun)

# Run the benchmark case
(cd interCondensateEvaporateFoam && ./Allrun)

# ------------------------------------------------------------------------------
